### ISSUE TITLE
Update 3.4.4 Z-wave not working anymore

### ISSUE THREAD

**Issue by HellStorm666** [openhab/org.openhab.binding.zwave#1874]
This issue list is to report bugs or enhancements for the openHAB Z-Wave binding. If you're not sure about something, please consider discussing it on the [forum](http://community.openhab.org) before raising an issue - more people follow the forum than monitor the issues list, so if you are having trouble with a device, or want to ask a question, you will have a much larger audience there.

In order to ensure we have the best information to deal with the issue, please fill in the following information (delete as necessary depending on the issue).

* OH2 Version: 3.4.4

If the problem is associated with a device, please provide the following -:

* Device name: Aeotec Z-Wave stick gen5
* Device version: 5a, man. 86

syslog says:
openHAB karaf[438]: java.lang.NoClassDefFoundError: Could not initialize class gnu.io.RXTXCommDriver thrown while loading gnu.io.RXTXCommDriver
This happend after the update to 3.4.4.
Problem is persistent after reboot.

**Comment by HellStorm666** [comment]
Ok... So, after a 2nd restart of the system it all works again.
